import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import ToasterProvider from "./provider";
import "./globals.css";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "BuildBot GH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ToasterProvider>{children}</ToasterProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
